In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition import PCA

In [ ]:
path = '/content/drive/MyDrive/train.csv'
data_frame = pd.read_csv(path)

print(data_frame.columns)

Index(['DATE (MM/DD)', 'MST', 'Global CMP22 (vent/cor) [W/m^2]',
       'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]',
       'Tower Dry Bulb Temp [deg C]', 'Tower Wet Bulb Temp [deg C]',
       'Tower Dew Point Temp [deg C]', 'Tower RH [%]', 'Total Cloud Cover [%]',
       'Peak Wind Speed @ 6ft [m/s]', 'Avg Wind Direction @ 6ft [deg from N]',
       'Station Pressure [mBar]', 'Precipitation (Accumulated) [mm]',
       'Snow Depth [cm]', 'Moisture', 'Albedo (CMP11)'],
      dtype='object')


In [ ]:
data = data_frame.drop(columns=['DATE (MM/DD)', 'MST', 'Global CMP22 (vent/cor) [W/m^2]',
       'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]',
       'Tower Dry Bulb Temp [deg C]', 'Tower Wet Bulb Temp [deg C]',
       'Tower Dew Point Temp [deg C]', 'Avg Wind Direction @ 6ft [deg from N]',
       'Station Pressure [mBar]','Snow Depth [cm]','Albedo (CMP11)'])
data1 = data.loc[data['Total Cloud Cover [%]']>-1]
data1 = data1.loc[data['Total Cloud Cover [%]']<101]
data2 = data1.iloc[1:,]
data1 = data1.iloc[:data1.shape[0]-1,]
# data1
# dataTemp = data_frame.drop(columns=['DATE (MM/DD)', 'MST', 'Global CMP22 (vent/cor) [W/m^2]',
#        'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]', 'Tower RH [%]','Peak Wind Speed @ 6ft [m/s]', 'Avg Wind Direction @ 6ft [deg from N]',
#        'Station Pressure [mBar]','Snow Depth [cm]','Albedo (CMP11)','Precipitation (Accumulated) [mm]','Moisture'])
# dataTemp = dataTemp.loc[dataTemp['Total Cloud Cover [%]']>-1]
# dataTemp = dataTemp.loc[dataTemp['Total Cloud Cover [%]']<101]
# dataTemp = dataTemp.drop(columns=['Total Cloud Cover [%]'])
# pca1 = PCA(n_components=1)
# dataTemp = pca1.fit_transform(X=dataTemp)

In [ ]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
X_train, y_train = data1,data2
rf = RandomForestRegressor(n_estimators = 500, random_state = 42)
rf.fit(X_train, y_train)

In [ ]:
def test_res(min,f_1):
  f = f_1
  for i in range(min):
    f1 = rf.predict(np.array(f).reshape(1,-1))
    f = f1
  return f

In [ ]:
result = []
for j in range(1,301):
  path = '/content/drive/MyDrive/test/'+str(j)+'/weather_data.csv'
  test_data = pd.read_csv(path)
  test_data['Time [Mins]'] = test_data['Time [Mins]'] + 7*60+40
  test_data = test_data.drop(columns=['Global CMP22 (vent/cor) [W/m^2]','Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]','Precipitation (Accumulated) [mm]','Snow Depth [cm]', 'Moisture', 'Albedo (CMP11)'])
  test = test_data.drop('Total Cloud Cover [%]',axis=1)
  c = test_data.drop('Time [Mins]',axis=1)
  tim = int(test['Time [Mins]'].iloc[test.shape[0]-1])
  res_30 = test_res(tim,30,test,c)
  res_60 = test_res(tim,60,test,c)
  res_90 = test_res(tim,90,test,c)
  res_120 = test_res(tim,120,test,c)
  print(res_30)
  print(res_60)
  print(res_90)
  print(res_120)
  tem_res = [res_30[:,4],res_60[:,4],res_90[:,4],res_120[:,4]]
  result.append(tem_res)

TypeError: ignored

In [ ]:
result = []
for j in range(1,301):
  path = '/content/drive/MyDrive/test/'+str(j)+'/weather_data.csv'
  test_data = pd.read_csv(path)
  testq = test_data
  test_data = test_data.drop(columns=['Time [Mins]', 'Global CMP22 (vent/cor) [W/m^2]',
       'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]',
       'Tower Dry Bulb Temp [deg C]', 'Tower Wet Bulb Temp [deg C]',
       'Tower Dew Point Temp [deg C]', 'Avg Wind Direction @ 6ft [deg from N]',
       'Station Pressure [mBar]','Snow Depth [cm]','Albedo (CMP11)','Tower RH [%]','Peak Wind Speed @ 6ft [m/s]','Precipitation (Accumulated) [mm]','Moisture'])
  # pca = PCA(n_components=1)
  # dataTemp_test = testq.drop(columns=['Time [Mins]', 'Global CMP22 (vent/cor) [W/m^2]','Total Cloud Cover [%]',
  #      'Direct sNIP [W/m^2]', 'Azimuth Angle [degrees]', 'Tower RH [%]','Peak Wind Speed @ 6ft [m/s]', 'Avg Wind Direction @ 6ft [deg from N]','Station Pressure [mBar]','Snow Depth [cm]','Albedo (CMP11)','Precipitation (Accumulated) [mm]','Moisture'])
  # dataTemp_test = pca.fit_transform(X=dataTemp_test)
  # test_data['Temp'] = dataTemp_test
  test = test_data
  f_1 = test_data.iloc[test_data.shape[0]-1,:]
  res_30 = test_res(30,f_1)
  res_60 = test_res(60,f_1)
  res_90 = test_res(90,f_1)
  res_120 = test_res(120,f_1)
  print(res_30)
  print(res_60)
  print(res_90)
  print(res_120)
  tem_res = [res_30[0],res_60[0],res_90[0],res_120[0]]
  result.append(tem_res)

[98.94012003]
[98.94012003]
[98.94012003]
[98.94012003]
[38.04235954]
[38.04235954]
[38.04235954]
[38.04235954]
[97.9678548]
[97.9678548]
[97.9678548]
[97.9678548]
[52.83591987]
[52.83591987]
[52.83591987]
[52.83591987]
[20.00352484]
[20.00352484]
[20.00352484]
[20.00352484]
[17.00298111]
[17.00298111]
[17.00298111]
[17.00298111]
[14.96172569]
[14.96172569]
[14.96172569]
[14.96172569]
[25.0560231]
[25.0560231]
[25.0560231]
[25.0560231]
[66.88714444]
[66.88714444]
[66.88714444]
[66.88714444]
[27.9868951]
[27.9868951]
[27.9868951]
[27.9868951]
[98.94012003]
[98.94012003]
[98.94012003]
[98.94012003]
[93.97413565]
[93.97413565]
[93.97413565]
[93.97413565]
[45.95182578]
[45.95182578]
[45.95182578]
[45.95182578]
[29.02070286]
[29.02070286]
[29.02070286]
[29.02070286]
[36.12257159]
[36.12257159]
[36.12257159]
[36.12257159]
[15.97182607]
[15.97182607]
[15.97182607]
[15.97182607]
[98.94012003]
[98.94012003]
[98.94012003]
[98.94012003]
[79.84200433]
[79.84200433]
[79.84200433]
[79.84200433]
[15.

In [ ]:
result

[[98.94012003042631, 98.94012003042631, 98.94012003042631, 98.94012003042631],
 [38.042359537638106,
  38.042359537638106,
  38.042359537638106,
  38.042359537638106],
 [97.96785480330912, 97.96785480330912, 97.96785480330912, 97.96785480330912],
 [52.83591986633469, 52.83591986633469, 52.83591986633469, 52.83591986633469],
 [20.003524835131874,
  20.003524835131874,
  20.003524835131874,
  20.003524835131874],
 [17.002981107237503,
  17.002981107237503,
  17.002981107237503,
  17.002981107237503],
 [14.961725689754303,
  14.961725689754303,
  14.961725689754303,
  14.961725689754303],
 [25.056023095307975,
  25.056023095307975,
  25.056023095307975,
  25.056023095307975],
 [66.88714444088546, 66.88714444088546, 66.88714444088546, 66.88714444088546],
 [27.98689510383208, 27.98689510383208, 27.98689510383208, 27.98689510383208],
 [98.94012003042631, 98.94012003042631, 98.94012003042631, 98.94012003042631],
 [93.97413565468175, 93.97413565468175, 93.97413565468175, 93.97413565468175],
 [

In [ ]:
resul = np.array(result)

In [ ]:
resul.shape

(300, 4)

In [ ]:
resul

array([[98.96205598, 98.96205598, 98.96205598, 98.96205598],
       [38.05451536, 38.05451536, 38.05451536, 38.05451536],
       [97.96947156, 97.96947156, 97.96947156, 97.96947156],
       ...,
       [12.99277224, 12.99277224, 12.99277224, 12.99277224],
       [36.99846769, 36.99846769, 36.99846769, 36.99846769],
       [27.00805963, 27.00805963, 27.00805963, 27.00805963]])

In [ ]:
path1 = pd.read_csv('/content/drive/MyDrive/qns/test1.csv')
path1

Unnamed: 0  Unnamed: 0.1  ...  90_min_horizon  120_min_horizon
0             0             0  ...              99               99
1             1             1  ...              39               39
2             2             2  ...              98               98
3             3             3  ...              53               53
4             4             4  ...              21               21
..          ...           ...  ...             ...              ...
295         295           295  ...              11               11
296         296           296  ...              55               55
297         297           297  ...              13               13
298         298           298  ...              37               37
299         299           299  ...              28               28

[300 rows x 10 columns]

In [ ]:
cols = ['30_min_horizon',	'60_min_horizon',	'90_min_horizon',	'120_min_horizon']

In [ ]:
from math import ceil

In [ ]:
les = []
for i in range(resul.shape[0]):
  for j in range(resul.shape[1]):
    les.append(ceil(resul[i][j]))

In [ ]:
les = np.array(les).reshape(300,4)
les

array([[99, 99, 99, 99],
       [39, 39, 39, 39],
       [98, 98, 98, 98],
       ...,
       [13, 13, 13, 13],
       [37, 37, 37, 37],
       [28, 28, 28, 28]])

In [ ]:
resul

array([[98.96205598, 98.96205598, 98.96205598, 98.96205598],
       [38.05451536, 38.05451536, 38.05451536, 38.05451536],
       [97.96947156, 97.96947156, 97.96947156, 97.96947156],
       ...,
       [12.99277224, 12.99277224, 12.99277224, 12.99277224],
       [36.99846769, 36.99846769, 36.99846769, 36.99846769],
       [27.00805963, 27.00805963, 27.00805963, 27.00805963]])

In [ ]:
# resul = resul.reshape(1,-1)
# les = les.reshape(300,4)
ref = pd.DataFrame(resul,columns=cols)
ref

30_min_horizon  60_min_horizon  90_min_horizon  120_min_horizon
0         98.940120       98.940120       98.940120        98.940120
1         38.042360       38.042360       38.042360        38.042360
2         97.967855       97.967855       97.967855        97.967855
3         52.835920       52.835920       52.835920        52.835920
4         20.003525       20.003525       20.003525        20.003525
..              ...             ...             ...              ...
295       10.070757       10.070757       10.070757        10.070757
296       54.039824       54.039824       54.039824        54.039824
297       12.994149       12.994149       12.994149        12.994149
298       37.041805       37.041805       37.041805        37.041805
299       26.998837       26.998837       26.998837        26.998837

[300 rows x 4 columns]

In [ ]:
path1[['30_min_horizon','60_min_horizon','90_min_horizon','120_min_horizon']] = ref

In [ ]:
path1.to_csv('/content/drive/MyDrive/qns/test1.csv')

In [ ]:
import pickle
filename = '/content/drive/MyDrive/qns/finalized_model_100.sav'
pickle.dump(rf, open(filename, 'wb'))

KeyboardInterrupt: ignored